### ISSUE TITLE
Adding an expense receipt fails and buttons become unresponsive

### ISSUE THREAD

**Issue by macjuan** [vaadin/expense-manager-demo#100]
Started up Expense Manager, added it to iOS 11.3 home screen and started the app. Added an expense and tried to add a receipt. Instead of showing the receipt it just shows bordered label "Receipt". Save, Cancel nor Delete buttons work. See attached video.
![img_8370 trim](https://user-images.githubusercontent.com/17796527/40622794-efc6ee44-62ab-11e8-907e-690253aadc7d.gif)

**Comment by macjuan** [comment]
Is this now fixed at https://expensemanager.demo.vaadin.com/ ?

**Comment by tomivirkki** [comment]
No, deploying to https://expensemanager.demo.vaadin.com/ is not in scope of this ticket. There are other fixes to be merged before we deploy the new version. The fix for this ticket is now in master so the ticket is considered done.

**Comment by manolo** [comment]
Tried to deploy but there are some issues in CI infra, they are working in a fix. I'll inform when the app is available

**Comment by manolo** [comment]
@macjuan  Deployed version in pro server works and have the fix if you want to check it out https://expensemanager-pro.demo.vaadin.com/

The normal version (open sourced) deployment is still failing.

**Comment by manolo** [comment]
@macjuan Finally everything is working fine. 
Now infra is configured that any new change in master is reflected in the site. CI takes care of it.
